.travis.yml
common/test/__init__.py
common/tools.py

This is more of an experiment for fun than anything else! (So you won't make me feel bad if you don't want it for any reason).
I'm a big fan of continuous integration systems for running compilation, tests, etc on every check-in. I've used Cruisecontrol, Hudson, Jenkins, and others for many years and they've been a big help. I've recently been exposed to [TravisCI](https://travis-ci.org/), a free CI service for open-source projects. It's very similar in features to the other big CI systems.
I tried my hand at adding a [TravisCI configuration file](https://docs.travis-ci.com/user/languages/python), and I created a travis CI account and [connected it to my personal BIT fork](https://travis-ci.org/dinoboy197/backintime). So anytime I check in to any of my fork's branches, the CI system …

Add travis CI support

---

common/snapshots.py
common/test/test_snapshots.py

Fixes #523:
1) [```path``` is bytes (and is asserted to be so) when it is set as the key to the fileinfodict](https://github.com/bit-team/backintime/blob/master/common/snapshots.py#L811)
2) [```path``` is still bytes when it's getting ready to be saved, but is now asserted to be a string - which fails instantly](https://github.com/bit-team/backintime/blob/master/common/snapshots.py#L2167).
I fixed a unit test which made an incorrect assumption about the ```fileInfoDict``` keys - it assumed they would be ```String```s from upstream in code in ```_take_snapshot()```, when in fact they are ```Byte``` arrays. Also verified that this fix allows snapshots to complete successfully.
@Germar - Seems like having a big end-to-end test of the snapshot and restore functionality would be good to ensure …

Fix file info persistence errors

---

common/snapshots.py
common/test/test_snapshots.py

Issue #523 :
Reading fileinfo currently doesn't read the path back in as binary, which is expected by downstream restore code. As a result, when files are restored they don't get their uid / gid / perms set because the paths restored don't exist as keys in the fileinfo dict (the dict keys are strings, but the path checked is bytes).
I've verified that this fix actually works - restored files now get their uid / gid / perms set correctly.

Fix file info reading

---

common/test/test_config.py
common/tools.py

I was working a bit with testing functionality in the ```config``` module, and I thought I'd start adding some unit tests!
And I found a bug by accident :) I'm not sure if I fixed in the way that is correct, as I'm not 100% sure about the usage of the ```parent``` kwarg in the ```logger.error()``` method.

Starting unit tests for config module

---

.travis.yml
common/encfstools.py
common/mount.py
common/snapshots.py
common/sshtools.py
common/test/test_encfstools.py
common/test/test_sshtools.py
qt4/settingsdialog.py

@Germar , per our email discussion this is part of the precursor work to moving towards full-rsync mode for all backup modes.
I thought it would be prudent to add read-only for mounts through fuse as a default constructor argument to the ```Mount``` object, in case there is a time in the future when mounting in non-read-only mode is desired. The UI or some other method calling into the ```Mount``` class could pass the read-only flag as they desire.
On testing - I'm not sure what the best way to unit-test or end-to-end test this is at the moment. I think I'd have to set up ssh for the test rig, which I think could be a bigger effort which might be better isolated in a different piece of work? What do you think?

Fuse mounts for SSH, Local Encrypted, and SSH encrypted are read-only by default

---

.travis.yml
common/cli.py
common/test/test_backintime.py
common/tools.py

I took the time to write the first end-to-end test of BIT :)
It's certainly not a full test suite, but we can build on this going forward. It gives us a place to start. I've written many such end-to-end tests for other software that I maintain professionally and I think approaching end-to-end tests as coded here are incredibly valuable for hard-to-spot regressions.
Ideas:
* test one of highest level interfaces - in this case, the command line - to ensure that everything from argument parsing, functionality, and output works as expected.
* Maybe in the future we can think about testing the GUI in an automated way (though that is out of my area of expertise)
* don't call python functions directly; instead, test what a command line user would use - the command line itself in a shell, by …

Added basic local snapshot end to end test

---

.travis.yml
README.md
common/bindfstools.py
common/cli.py
common/config.py
common/mount.py
common/snapshots.py
common/test/generic.py
common/test/test_backintime.py
common/test/test_bindfstools.py
debian/control
qt4/settingsdialog.py

* Added bindfs as an optional dependency
* Changed all local mode usage to bindfs, mounting r/w for snapshotting and r/o for all other operations (same as ssh, local_encfs, ssh_encfs)
* Fixed a couple of bugs which integration tests found
* Added a ```get_local_path``` and ```set_local_path``` method pair in the ```Config``` class for shuttling the snapshot path that the user selects (without it being conflated with the ```get_snapshot_path```, which is overloaded for use with the bindfs mount point)

Local mode mounts over bindfs

---

qt4/app.py

Bug appearing after 1.1.12 - cannot use the UI to navigate the filesystem of a snapshot.
Turns out that the ```open_path()``` method of the app.py is calling ```SID.canOpenPath()``` with a full snapshot path, rather than a path relative to the snapshot itself. ```SID.canOpenPath()```'s contract is that it takes a relative path.
I fixed the three instances where ```SID.canOpenPath()``` is called, to ensure that relative paths are used.
Note that I don't have a mouse with buttons 4 and 5, so I can't test the fix in those two areas (navigating backward and forward in history).
At the moment, I can't create a regression test to prevent this from re-occuring (because this is a problem of the UI module not adhering to the API contract of the backend module), but I am looking into PyQT's …

QT4 UI should send relative path to SID.canOpenPath, not fullPath

---

CHANGES
common/plugins/usercallbackplugin.py
common/snapshots.py

I modified snapshots.py so that if the lock file ~/.local/share/backintime/worker2.lock still exists when it shouldn't, then the warning message is more helpful: it tells you where the problem is.

gives more helpful advice if a log file is present that shouldn't be.  (https://github.com/bit-team/backintime/issues/601)

---

common/backintime.py
common/configfile.py

This is my first PR here. So it is kind of a practice for me. ;)
Sorry for promoting two modifications in one PR. This is uncommon an I will do it better next time. Hope this is ok today.
1.
In `configfile.py`: `profilesSortedByName()`
The dictionary there now is ordered a more pythonic way. It depends on the offical documentation.
2.
In `backintime.py`:
This is the main reason for this PR.
In the debug output not the ProfileID is "connected" with the ProfileName.
I am not sure if this is the best solution. Maybe I should add a new methode to `class ConfigFileWithProfiles` like `def profilesIdNames()` returning a dictionary?

improved debug output to identify profiles

---

README.md
common/tools.py

Use long versions of the rsync options. E.g. `--perms` instead of `-p`.
This make it easier to understand the code, the debug messages and doing diagnosis.
btw: unitest on my own machine is not possible currently because of problems in the test-suite. Germar knows about it and work on it.

using long versions of rsync options

---

common/mount.py
common/tools.py

Github merge request port of path supplied in 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946349
This measure especially protects the root of a already mounted file system
(ssh or encfs) from getting its access permissions altered.
Should fix #974 and #954

Keep permissions of an existing mountpoint from being overridden

---

common/password_ipc.py

After some investigation, #1134 seems to be a rather simple problem: The `TempPassThread` object in question calls the method `isAlive` which has been removed (at least in Python 3.9) in favor of `is_alive`.

Fix #1134: 'TempPasswordThread' object has no attribute 'isAlive' (Python 3.9)

---

common/tools.py

Newer rsync versions have a different version style now, which breaks the regex match to add the progress2 capability. This adds a new regex match so that this gets correctly detected to show progress in for example the QT GUI
Fixes #1138

Match old and new rsync version format

---

qt/settingsdialog.py

This removes the Qt.lightGray Color for the excluded list in the settings, which does not work well with KDE theming, especially dark themes. It uses the link-color instead, which gets themed and looks better (on KDE)
I am not sure if this is a good color choice, but i am not familiar enough with the Qt -framework.

Use Link Color instead of lightGray as not to break theming

---

qt/plugins/notifyplugin.py

This fallback code I found while developing something else does not really set `self.user` but creates and sets a new local variable called `user`, which is and can never used afterwards.

qt/plugins/notifyplugin: Fix setting self.user, not local variable

---

common/mount.py

If the user manually unmounts the drive containing the mount dir in the user-callback script, then os.listdir(self.currentMountpoint) will throw an exception, as the directory won't exist.
This PR avoids the following exception
```
INFO: mount ssh: backups@domain:/media/user/drive/path on /home/user/.local/share/backintime/mnt/ID/mountpoint
[...]
INFO: Create info file
Traceback (most recent call last):
File "/usr/share/backintime/common/backintime.py", line 1165, in <module>
startApp()
File "/usr/share/backintime/common/backintime.py", line 517, in startApp
args.func(args)
File "/usr/share/backintime/common/backintime.py", line 739, in backup
ret = takeSnapshot(cfg, force)
File "/usr/share/backintime/common/backintime.py", line 94, in takeSnapshot
ret = …
```

Fix FileNotFoundError exception in mount.mounted

---

common/backintime.desktop

As it happens with other programs (https://github.com/nextcloud/desktop/pull/4194 , 
https://invent.kde.org/pim/knotes/-/commit/70e81d7286c83ff28deadb2f2b80e67b463d1db7 ,
https://github.com/qbittorrent/qBittorrent/pull/15996 ,
https://nicolasfella.de/posts/taskbar-single-app ,
https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/53):
There can only be one instance of the program running. Mark it as such in 
the .desktop file. This allows desktop environments to adjust their UI 
accordingly.

Mark BackInTime as a single main window program

---

common/man/C/backintime-config.1

This fix updates the outdated documentation discovered in the issue #1270
You can preview the updated man page in the console via.
`man -l backintime.config.1`
This pull request should close the issue.

Fixes #1270 (schedule.time doc outdated)

---

.gitignore
common/configure
common/test/__init__.py

I have implemented my DEV feature request now.
To test the new `make` target:
```
cd common
./configure
make coverage
```
@emtiu Could you please check and merge my PR? THX!

Closes #1279: Add code coverage of unit tests as MAKE target

---

.travis.yml

This PR disables Python testing for versions `3.9-dev` and `nightly` on AMD64 architecture, to keep the testing to a necessary minimum.

test: Update Travis CI file for better testing.

---

qt/app.py
qt/settingsdialog.py

Adds accelerator keys to the menu bars and tabs in the settings screen. Most of the toolbar buttons now also have shortcut keys for easier keyboard access. This also removes the exit button from the toolbar and changes the shortcut to the more standard CTRL + Q instead of CTRL + W which is often used for closing tabs
Closes #1104, closes #172

Shortcuts for menu bar and tabs, toolbar items and remove exit from toolbar

---

qt/snapshotsdialog.py

`QLineEdit.text()` returns `str` which don't have `toUtf8` method.
Later an command is build up based on this input. I have tested
that it still works with unicode characters.

Fix: `str` don't have `toUtf8` method.

---

common/config.py
common/test/config
common/test/test_backintime.py

My apologize that this PR is not atomic.
Replaced deprecated `assertEquals()` with `assertEqual()` (no "s" at the end).
Improved readability in a test file following PEP8.
Upgraded the config file in the test suite to the current format. Previously the problem was that it was automatic upgraded by BIT itself when running unittests. As a result `common/test/config` changed it's git-state to "modified".

test_backintime: Fix DeprecationWarning, more PEP8 and upgraded test-config-file

---

common/tools.py

@emtiu If have fixed this and performed the following manual tests successfully, please merge if OK:
1. Empty crontab file (zero bytes)
2. crontab file with one empty line "\n\n" (no real text contained)
3. crontab file with one text line ("# test")
I have run the unit test for all three scenarios...

Closes #1181: test_readWriteCrontab fails when crontab is empty

---

common/tools.py

This eleminates some `DeprecatedWarning` while running tests.
The class `distutils.version.StrictVersion` doing version comparison and its package `distutils` is deprecated. They are replaced by `packaging.Version` (see [PEP440](https://peps.python.org/pep-0440/)).

fix: deprecated StrictVersion

---

CHANGES

Sources for missing entries (versions 1.1.14 through 1.1.24):
* https://launchpad.net/backintime/+series (and subpages)
Sources for release dates (sorted from recent to ancient):
* https://launchpad.net/backintime/+series
* https://bazaar.launchpad.net/~bit-team/backintime/main/changes?filter_path=VERSION
* https://web.archive.org/web/20130330000754/http://backintime.le-web.org/category/news/ (and further pages)

CHANGES: complete history

---

CHANGES
common/backintime.py
common/test/test_backintime.py

**THIS IS A PREVIEW FOR DISCUSSIONS - PLEASE DO NOT YET MERGE INTO MASTER**
I have created a first PR to make the location and file name of the user-callback script visible.
Applied changes:
1. `backintime` now shows the same content as before + (new!) the user callback location (I call this: "about" `backintime`)
2. `backintime -v` did show only the version number. It now shows the same "about" output as above
The main reason for 2. was that 1. is not obvious to call and 2. does not hurt (having a longer output now).
The version number can still be easily parsed via a regexp (if someone really needs to do so).
**Open:**
- I did not (yet) implement the syslog output whenever the user-callback is called (could also be a second PR)
**Out of scope:**
- #827 (together with #1292): I would …

Release candidate for FR #1100 (unclear user-callback location)

---

common/sshtools.py

While I was working with something else, I was filed with this. 😄 
So I did some PEP8 improvement.
btw: `pytest` captured two warnings about escape sequences.
```
'echo \"rmdir \$(mktemp -d)\"; tmp3=$(mktemp -d); test -z "$tmp3" && cleanup 1; rmdir $tmp3 >/dev/null; err_rmdir=$?; '
^
'echo \"rmdir $(mktemp -d)\"; tmp3=$(mktemp -d); test -z "$tmp3" && cleanup 1; rmdir $tmp3 >/dev/null; err_rmdir=$?; '
```
In my understanding there is no need for escaping an `$` and all tests **on my machine** are green. But Travis has a problem with it and I don't understand why.
The second warning needs also further knowledge and investigation. Later...

fix: PEP8 in sshtools

---

common/test/test_snapshots.py
common/test/test_sshtools.py
common/test/test_tools.py

This an exotic PR because it doesn't close an Issue but [open it](#1297).
Some unitests where skipped because of constructs like that
```
@unittest.skip('Not yet implemented')
def test_inhibitSuspend(self):
pass
```
To clean up the test summary I removed them all and collect them in #1297 for further investigation. Only one skipped test is left: #1298 
Everything green except one

Removed Not-yet-implemented tests

---

.travis.yml
CHANGES
common/diagnostics.py
common/test/test_diagnostics.py

Related to https://github.com/bit-team/backintime/pull/1295
Introducing the module `backintime.diagnostics` in `common/diagnostics.py`.
Collect information' useful for debuging about Bit, the operating system, used packages and "external" comandline tools. The result is a nested `dict`.
This is an example output
```
{
"backintime": {
"name": "Back In Time",
"version": "1.3.2",
"config-version": 6,
"distribution-package": "/home/user/ownCloud/my.work/bit/backintime",
"git-branch": "diag",
"git-hash": "527da39d887e1029b4aec57444ea45861e4514db"
},
"paths": {
"common": "/home/user/ownCloud/my.work/bit/backintime/common"
},
"running_as_root": false,
"python": "3.9.2 default Feb 28 2021 17:03:44 CPython GCC 10.2.1 20210110",
"platform": "Linux-5.10.0-18-amd64-x86_64-with-glibc2.31",
"system": …
```

Collect diagnostic informations

---

common/config.py

Because of the value of `config.Config.CONFIG_VERSION` the current version of the config files used by the latest stable BIT release is `6`.
This fix take care that this number is used by default for (empty) config files that don't specify `config.version` by their own.
This problem was introduced by [a commit in the year 2016](https://github.com/bit-team/backintime/commit/72fc4908f083e57cb059cd9cde2175d61bd9274a).
In the wild with normal users this touch only some edge cases. But it is highly relevant for unittesting where some of tests do use empty config files.
This PR also [solves a problem and the need for an associated workaround](https://github.com/bit-team/backintime/blob/be3c256351145b58e11f9363715a3c904aec1f65/common/test/test_backintime.py#L179-L182) encountered by @aryoda. The …

fix: Using correct default number as config version.

---

CHANGES
common/test/test_tools.py
common/tools.py

I was on the way to investigate and fix our rsync-problem. But on that dirty road I found two tiny warnings about deprecated escape sequences in two regex patterns. Not a big deal. I fixed this. But to write good unittests for that I needed to refactor some code.
The function `tools.uuidFromDev()` was to complex. I split up that code and created three additional and private functions that are used by `uuidFromDev()`. And I add some unittests for it.
Took some time. ;)

Fix deprecation warnings / Refactoring uuidFromPath incl. unittests improvment

---

common/backintime.py
common/diagnostics.py
common/test/test_backintime.py
common/test/test_diagnostics.py

Integrates:
* #1295
* #1300
Changes:
* Add user-callback path to collect_diagnostics() to avoid regression
* Remove TravisCI test failure workaround (was fixed with #1305)
* Correct some typos in comments.

Integrate extended diagnostics (#1300 with #1295)

---

common/encfstools.py
qt/qttools.py

The class `distutils.version.StrictVersion` doing version comparison and its package `distutils` is deprecated. They are replaced by `packaging.Version` (see [PEP440](https://peps.python.org/pep-0440/)).
This is related to #1288 where I did the same but obviously missed some parts of the code. Not sure why I missed them. It seems to me that this DeprecationWarning doesn't occur with Python 3.9 but 3.10. Now I search via `grep` for the use of `distutils` package. I suspect that the deprecated `distutils` package isn't used anymore.

Fix DeprecationWarning about StrictVersion

---

common/diagnostics.py
common/test/test_diagnostics.py

Extend diagnostic information's
1. Python executable path.
2. Rsync environment variables.
3. Modified username replacement to replace users homepath and not only its username.
4. PEP8 etc
About 1: Related to #1316 where the path to systems python interpreter was "hacked" via "pyenv". This info will catch situations like that.
About 2: Related to #1247. Rsync 3.2.4 do use a different way of argument protection. The situation is complex and the environment variables RSYNC_OLD_ARGS and RSYNC_PROTECT_ARGS to influence that.
About 3: The replacement is done on the whole JSON-like string and not on specific elements. To prevent replacement of technical informations (e.g. about "rsync") when a user do use a technical login name (e.g. "rsync") now we search for the users homepath and not only is …

feat: Extend diagnostic information's

---

.gitignore

Exclude files like that from git
`common/.myrsync.sh.swp`
This is a temporary file created by `vim`.

Exclude vim temporary files via gitignore

---

CHANGES
README.md
common/diagnostics.py
common/tools.py

due to "no appropriate keyring found"
* Add more DEBUG output to tools.keyringSupported()
* Add "keyring-supported" to "--diagnostics" output
* Add diagnostic and how-to-fix doc around `keyring` to README.md

Fix #1321: Settings GUI: "Save password to Keyring" was disabled

---

CHANGES
common/config.py
common/snapshots.py

Fixes one half of #1142, closes #1143.

Improve logging for canBackup check

---

common/snapshots.py

This reduces the verbosity of target wait cycles to DEBUG and emits a single INFO log if the target was not found on the first check iteration.
Please take a look.

Don't spam log with waits

---

CHANGES
qt/qttools.py

Tested on Manjaro KDE Plasma with Wayland for normal and root user: Boot GUIs show the disk icon now...

Fixes 1244: KDE/Wayland: Wrong icon in taskbar (default Wayland instead of BiT icon)

---

CHANGES
README.md
common/test/test_backintime.py
common/tools.py

Fix bug: BiT does not start with DBus exception NameHasNoOwner (partial fix for #921). Also fixes Arch Linux build error (#1233).
* Fix the BiT CLI side of the bug #921
* serviceHelper system D-Bus daemon issues are still under investigation
* Fix Arch Linux build test and installation failure (#1233)
* Add better documentation for installation on Arch using AUR package to README

Fix bug: BiT does not start (DBus exception NameHasNoOwner)

---

CHANGES
common/logger.py
common/test/test_backintime.py

* Affects logger.info and logger.debug
* complies now to the behavior of pythons's standard logging package
Our logging system pollutes the normal (non-logging) stdout output with logging output, we need a clear separation here
(eg. logging to stderr instead of stdout) otherwise we can never separate normal from (partially random) logging output in unit tests.
Standard python's logger package says:
> If you call the functions [debug()](https://docs.python.org/3/library/logging.html#logging.debug), [info()](https://docs.python.org/3/library/logging.html#logging.info), [warning()](https://docs.python.org/3/library/logging.html#logging.warning), [error()](https://docs.python.org/3/library/logging.html#logging.error) and [critical()](https://docs.python.org/3/library/logging.html#logging.criti …

Write all log output to stderr (do not pollute stdout)

---

common/mount.py
common/snapshots.py
common/test/generic.py
common/test/test_snapshots.py

Introducing class `test_snapshots.py::TestSshPermissions` testing `snapshots.py::Snapshot.backupPermissions()` in a "SSH local" environment.
The case was untested before. Especially it is needed to support the fix of #1247 (rsync incompatibility).
I slightly improved the method `Snapshots.backupPermissions()` because before it was silent and didn't care about if the used `rsync` call succeeded or not. No the return code of `rsync` is returned and can be used in a unittest.
The "helper" functions in `test_snapshots.py` are refactored and improved a bit. Now they are used by this new `TestSshPermissions` and the before introduced `TestSshRemoveSnapshot` tests.

Test backing up permissions in a "SSH local" profile.

---

CHANGES
common/config.py
common/snapshots.py
common/sshtools.py

This fix `DeprecationWarnings` about _invalid escape sequences_. Most of that warnings are caught when running `pytest`. That warnings will become serious errors in future Python versions.
This where the warnings. Sorry for providing a screenshot instead of plain text but I still have problems copy & past from a Windows terminal window running ssh client and tmux.
Of course, I checked all problems and what that strings really need to do.
Most of the warnings are about `\$` which I modified to `\\$`. It is like escaping and escape. Sounds wired but it is intended to be that way. Because that string is handed over (via `subprocess.Popen()`) to a shell command (ssh) which need to receive a string containing an escape.

Fix: Invalid escape sequences

---

common/sshtools.py
qt/settingsdialog.py

- Eliminated possible deprecation warnings about invalid escape sequences ([W605](https://www.flake8rules.com/rules/W605.html))
- Eliminated round about 800 PEP8 problems in `settingsdialog.py`
- I didn't touched `create-manpage-backintime-config.py` because of #1354 
I was search for invalid escape sequences via `flake8`.

Fix: Invalid escape sequence warnings and some PEP8

---

common/diagnostics.py
common/test/test_backintime.py
qt/qttools.py

I have fixed all known issues on our side an try to contact the package maintainer now asking
- to fix the missing dependencies
- to reconsider setting LC_ALL=C for `make`ing
On my arch VM the build & unit tests are working now (after manually installing the required dependencies)...
Fixes #1333

Fix #1333: arch Linux build fails

---

common/diagnostics.py
common/test/test_diagnostics.py
common/test/test_tools.py
common/tools.py

The underlying problem was building from a path that is not names "backintime" as Git project root folder...
* The test failed on Arch but could also fail on any other distro
* Remove duplicated "distribution-package" node in diagnostics JSON output
* Add "git-project-root" to diagnostics JSON output
Tested on Ubuntu 20.04 and Arch

Fix #1356 (failing unit test test_distro_package_folder in test_diagnostics.py)

---

.travis.yml
common/config.py
common/create-manpage-backintime-config.py
common/man/C/backintime-config.1

While investiagting the manpage creation script some comments where added. Also some code formatting was done to improve readability and better fitting PEP8 rules.
Also repaired special #? comments accidentially removed in PR #1313 before.
Related to #1354

Code comments and PEP8 prettification.

---

common/config.py
common/sshMaxArg.py

* Now all profiles with ssh mode are probed for the max ssh cmd length
* Code doc for config property "sshMaxArgLength" updated (used to generate man pages)
* Fix some minor documentation issues
+ Unit tests did work
Output is now:
```
> python3 sshMaxArg.py
Profile 1 - Main profile: Mode = local
Profile 2 - profile 2: Mode = local
Profile 3 - test2config: Mode = local
Profile 4 - ext dev test: Mode = local
Profile 5 - ssh-hello-world: Mode = ssh
Tried length 1,048,320... Python exception: "Argument list too long". Decrease by 524,160 and try again.
Tried length 524,160... Python exception: "Argument list too long". Decrease by 262,080 and try again.
Tried length 262,080... Python exception: "Argument list too long". Decrease by 131,040 and try again.
Tried length 131,040... Can be …
```

Fix bug: sshMaxArg main function was using only the first profile

---

README.md
qt/icon.py
qt/qttools.py

* Show QT QPA platform plugin in app window title for "--debug"
* Show "root" in app window title if running as root
This is a partial "fix" for #1364 by adding debug output and documenting icon problems as known issue

Add logging for Qt5 platform, style, theme and system tray.

---

CHANGES
common/snapshotlog.py
common/tools.py

* RuntimeError "reentrant call inside io.BufferedWriter" in logFile.flush()

Fix #1003: RTE in logFile.flush() during backup

---

FAQ.md
README.md

- created `FAQ.md`
- moved Wiki FAQ into that file
- moved "hardware specific FAQ" from Wiki into  that file
- converted into Markdown syntax
- added topic "WARNING: BIT is already running" (because of #1387)
Now it is easier to review modifications on the FAQ.
After this is merged we can clean the Wiki section and add a link to `FAQ.md` into it.

Moved FAQ Wiki into a Markdown file

---

debian/control

Proposed hotfix for #1401.
Needs to be merged into
* main
* dev (must be done in the cmd line I guess since the Github GUI does support only one target branch for a PR):
`git switch dev` + `git merge main`

Hotfix for issue #1401 (missing dependencies in Ubuntu PPA package)
